version: 0.2

phases:
  build:
    commands:
      - |
        pip install pytest
        pytest tests/
        aws s3 cp etl_job.py s3://surajb-bucket202506/scripts/job-${CODEBUILD_BUILD_NUMBER}.py
        echo "{\"ScriptLocation\": \"s3://surajb-bucket202506/scripts/job-${CODEBUILD_BUILD_NUMBER}.py\"}" > artifact.json

artifacts:
  files:
    - artifact.json